import EcomFooter from "../components/EcomFooter";
import EcomFooterBanner from "../components/EcomFooterBanner";
import EcomHeader from "../components/EcomHeader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
        <EcomHeader/>
        {children}
        <EcomFooterBanner />
        <EcomFooter />
      </body>
    </html>
  );
}
