import AppDownload from "../components/AppDownload";
import BottomNavbar from "../components/BottomNavbar";
import DashBoardHeader from "../components/DashBoardHeader";
import Sidebar from "../components/Sidebar";

export const metadata = {
  title: {template: '%s | Fleket'},
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
        <AppDownload />
        <DashBoardHeader />
        {children}
        <BottomNavbar />
        <Sidebar />
      </body>
    </html>
  );
}
