import DashBoardHeader from "../components/DashBoardHeader";
import Footer from "../components/Footer";

export const metadata = {
  title: {template: '%s | Fleket'},
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
        <DashBoardHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
