import EcomFooter from "../components/EcomFooter";
import EcomFooterBanner from "../components/EcomFooterBanner";
import EcomHeader from "../components/EcomHeader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {

  const storeId = params.storeId

  return (
    <html lang="en">
      <body className={``}>
        <EcomHeader storeId={storeId}/>
        {children}
        <EcomFooterBanner />
        <EcomFooter />
      </body>
    </html>
  );
}
